bots:
  - name: 'test-bot'
    websites:                                 # (required) websites to forward tweets from
      - domain: 'https://x.com'              # (required) website domain, notice the slash at the end
        paths: ['user1', 'user2', 'user3']             # (required) users to forward tweets from
        cookie_file: './assets/cookies.json'
        config:
          cron: '0-59/5 4-23 * * *'
          translator:                         # (not required) translator
            type: 'gemini'
            key:  'api-key'
      - domain: 'https://x.com'              # (required) website domain, notice the slash at the end
        paths: ['user4', 'user5', 'user6']             # (required) users to forward tweets from
        cookie_file: './assets/cookies.json'
        config:
          cron: '1-59/5 4-23 * * *'
          translator:                         # (not required) translator
            type: 'gemini'
            key:  'api-key'
      - domain: 'https://x.com'              # (required) website domain, notice the slash at the end
        paths: ['user7', 'user8', 'user9']             # (required) users to forward tweets from
        cookie_file: './assets/cookies.json'
        config:
          cron: '2-59/5 4-23 * * *'
          translator:                         # (not required) translator
            type: 'gemini'
            key:  'api-key'
      - domain: 'https://x.com'
        task_type: 'follows'                  # (not required) task type
        task_title: '【Follows】'             # (not required) task title
        paths: ['user1', 'user2']             # (required) users to forward tweets from
        config:
          cron: '0 23 * * *'
          interval_time:
            max: 0
            min: 0
    forward_to:                               # (not required) forward to multiple platforms, you can add more than one
      - type: 'telegram'                      # (required) forward type
        token: 'bot:token'   # (required) telegram bot token
        chat_id: 'chat_id'
      - type: 'bilibili'
        token: 'bilibili-token'
    configs:                                  # (not required) forwarder configurations
      user_agent:  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0'                 # (not required) puppeteer supported user agent
      cron: "*/5 4-23 * * *"                   # (not required) cron job
      interval_time:
        max: 15000
        min: 5000
        
